services:
  app:
    image: kdm1/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - code:/app
    command: make test
volumes:
  code: {}
