services:
  app:
    image: kdm1/devops-for-programmers-project-lvl1
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - code:/app
    command: make test
  db:
    image: postgres:13
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
#    env_file:
#      - .env

volumes:
  code:
  pgdata:
