name: ci

on:
  push:
    branches:
      - 'master'

env:
  APP_IMAGE_NAME: kdm1/devops-for-programmers-project-lvl1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build App
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest

      - name: Image digest
        run: |
          echo ${{ env.APP_IMAGE_NAME }}
          echo ${{ steps.docker_build.outputs.digest }}
